# -*- coding: utf-8 -*-
"""Lab 3_Vulnerabilities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RMQik63pIt01U-GSwh2k2j-TZLjP9-kY

##Vulnerability 2

###Location
File: app.py

nonce = b'0123456789abcdef'
cipher = AES.new(key, AES.MODE_EAX, nonce=nonce)

###Description
A static nonce value is used while performing the encryption of passwords using AES-EAX encryption technique. Nonce is supposed to be unique for every encryption process. The reuse of the same nonce would make the encryption less secure and would disclose the relationship among the encrypted values.

###Impact
An attacker who breaks into an encrypted password value is capable of conducting cryptanalysis on the passwords that have been stored. This compromises the confidentiality of authentication information and poses additional risks to system security.

###Fix
Generate a new random nonce for every encryption operation using:

get_random_bytes(16)

###Testing
1. Encrypt the same password twice
2. Verify that the ciphertext values are different.
3. Confirm that authentication continues to function properly after implementing random nonce generation.

##Vulnerability 3

###Location

File: SampleNetworkClient.py

msg, addr = s.recvfrom(1024)

###Description
The client will be doing the blocking socket read calls without setting any time-out value. In case the server does not respond, then the application keeps on waiting for the response. This vulnerability may be exploited by an attacker.

###Impact
Users may be unable to retrieve temperature information or issue incubator commands. This can reduce availability of the monitoring system and impact patient care operations.

###Fix
Implement socket timeouts

s.settimeout(3)

###Testing
1. Start the application normally.
2. Stop the server process.
3. Request a temperature reading.
4. Verify the application returns an error message rather than hanging indefinitely.

##Vulnerability 4

###Location
Files: SampleNetworkClient.py & SampleNetworkServer.py

Client:
payload = bytes((tok + ";GET_TEMP"), 'utf-8')

Server:
cmds = msg.split(';')

###Description
The application creates protocol messages by simply appending authentication tokens within command strings. The server uses semicolons as delimiters for the commands. A malicious user who is capable of modifying the values of these tokens could potentially add commands to the message.

###Impact
Successful command injection could allow unauthorized protocol actions, resulting in improper system behavior or unauthorized modification of incubator settings.

###Fix
Validate token values before use. Tokens should contain apprived characters and conform to an expected format

ie:
 ^[A-Za-z0-9]{16}$

###Testing
1. Attempt to submit a token containing semicolons.
2. Verify the request is rejected.
3. Confirm valid tokens continue to function correctly.
"""